[theme]
# Primary theme color
primaryColor = "#1E2DBE"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for the sidebar
secondaryBackgroundColor = "#F8F9FA"

# Text color
textColor = "#2C3E50"

# Font family - removed to allow custom CSS font override
# font = "sans serif"
font = "Noto Sans"

[server]
# Disable CORS protection for local development
enableCORS = false
enableXsrfProtection = false

[browser]
# Automatically open browser when starting
gatherUsageStats = false